services:
  fitboisbot-db:
    image: "mariadb:latest"
    container_name: fitboisbot-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fitbois
      MYSQL_USER: fitboi_user
      MYSQL_PASSWORD: fitboi_4er!
      MYSQL_ROOT_PASSWORD: fitboi_4er!
