version: "3.7"
services:
  spring_service:
    build: .
    restart: always
    depends_on:
      - mysql_db
    links:
      - mysql_db:app_db
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fitbois
      MYSQL_USER: fitboi_user
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: